### ISSUE TITLE
Build Failure When Following the Instructions for 1.1

### ISSUE THREAD

**Issue by ahagenbruch** [agazzarini/SolRDF#116] opened 2015-10-21 10:16 UTC
When I'm running the instructions I get into the following error in the first step:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Solr RDF plugin .................................... SUCCESS [  0.905 s]
[INFO] solrdf-core ........................................ SUCCESS [  5.987 s]
[INFO] solrdf-client ...................................... SUCCESS [  0.931 s]
[INFO] solrdf-integration-tests ........................... FAILURE [  7.090 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.987 s
[INFO] Finished at: 2015-10-21T11:56:43+02:00
[INFO] Final Memory: 60M/1362M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.6:verify (default) on project solrdf-integration-tests: There are test failures.

**Comment by agazzarini** [comment] 2015-10-21 10:36
Hi @ahagenbruch, in the target folder you should find the surefire reports that contain the info about the failed tests, could you please send me them? In the meantime, just to reproduce the problem, could you please give me some info about your environment (OS, JVM version)? 

Thx

**Comment by agazzarini** [comment] 2015-10-21 10:37
If you get the failed test in the surefire reports, you can paste here the stacktrace, otherwise send me the files, I will find that information.

**Comment by ahagenbruch** [comment] 2015-10-21 10:53
You can find the files here: https://seafile.noc.ruhr-uni-bochum.de/d/b30b51f085/
I'm running on CentOS 7, Java 1.8.0_60, and Maven 3.3.1

**Comment by agazzarini** [comment] 2015-10-21 10:57
Just a brief note: I think that has nothing to do with your error, but I made a change to the installation notes, removing these steps

```
# cd solrdf-integration-tests
# mvn clean package cargo:run
```
There's no Cargo and this snippet was an erroneus copy and paste from 1.0. 
I'm checking your files

**Comment by agazzarini** [comment] 2015-10-21 11:09
That's really strange, I don't have this error on my local servers, but I got the same on Jenkins [1] (and it didn't send me any email about that :( but this is another issue).  

I need some more time. In the meantime, as a workaround, if you want to skip the tests you can do 

```
mvn -DskipTests clean install
``` 

-----------------------
[1] http://178.239.178.241:9090/jenkins/job/SolRDF/23/org.gazzax.labs$solrdf-integration-tests/testReport/org.gazzax.labs.solrdf.integration.sparql/Issue112_ITCase/deleteEverythingWithDateObject/

**Comment by agazzarini** [comment] 2015-10-21 15:03
Hi @ahagenbruch the problem has been fixed, I tried in my servers and in Jenkins [1] and now everything seems ok. Let me know if things are working for you, too. I will close this issue in that case.

On top of that, I think this is a really bad (read: technical) way to provide a try of SolRDF because you have to fight with technical details like Maven and so on. So, I think I will provide two installation guide: a "build from source" with the current instructions and a "solr.home" directory already built for having that immediately without even cloning the repository.

Does it make sense? I will copy this message also in the mailing list.    
-----------------------------------
[1] http://178.239.178.241:9090/jenkins/job/SolRDF/

**Comment by agazzarini** [comment] 2015-10-21 17:10
Hi @ahagenbruch I'm going to close this issue: I stressed a lot of my colleagues and we are sure that the issue has gone. Hopefully you will get the same behaviour, otherwise please reopen it!

**Closed by agazzarini** 2015-10-21 17:10 UTC
Labels: bug

**Comment by ahagenbruch** [comment] 2015-10-21 17:53
You can find the files here: https://seafile.noc.ruhr-uni-bochum.de/d/b30b51f085/
I'm running on CentOS 7, Java 1.8.0_60, and Maven 3.3.1

**Comment by ahagenbruch** [comment] 2015-10-21 18:05
Thanks a lot, Andrea, works like a charm now!
