### ISSUE TITLE
Querying string literals with diacritics or angle brackets yields no result

### ISSUE THREAD

**Issue by ahagenbruch** [agazzarini/SolRDF#53] opened 2015-04-15 07:35 UTC
I have indexed a dump of the authority data by the German National Library (cf. http://d-nb.info/standards/elementset/gnd). When I now query for objects including diacritical marks or angle brackets the relevant triples can't be found.

For example the GND holds information on "Frühe Neuzeit" (Early Modern Period):
```bash
curl  "https://api.ub.rub.de/gnd/sparql" --data-urlencode "q=PREFIX gndo:<http://d-nb.info/standards/elementset/gnd#>; SELECT * WHERE {<http://d-nb.info/gnd/7503866-3> ?p ?o }" -H "Accept: application/sparql-results+json"
```

But when I query for "Frühe Neuzeit" I get an empty result:
```bash
curl "https://api.ub.rub.de/gnd/sparql" --data-urlencode "q= SELECT * WHERE { ?s <http://d-nb.info/standards/elementset/gnd#preferredNameForTheSubjectHeading> 'Frühe Neuzeit' } LIMIT 1" -H "Accept: application/sparql-results+json"
```

Whereas querying for something without diacritics works as expected:
```bash
curl "https://api.ub.rub.de/gnd/sparql" --data-urlencode "q= SELECT * WHERE { ?s <http://d-nb.info/standards/elementset/gnd#preferredNameForTheSubjectHeading> 'Extrapyramidales Syndrom' } LIMIT 1" -H "Accept: application/sparql-results+json"
```
Another critical case is querying for something with angle brackets:
```bash
curl "https://api.ub.rub.de/gnd/sparql" --data-urlencode "q= SELECT * WHERE { ?s <http://d-nb.info/standards/elementset/gnd#preferredNameForTheSubjectHeading> 'Konfiguration <Informatik>' } LIMIT 1" -H "Accept: application/sparql-results+json"
```

Hope you can shed some light on why this is going wrong...

**Comment by agazzarini** [comment] 2015-04-15 16:55
Hi @ahagenbruch many thanks for entering this and sorry for delay in response...I'm receing too many emails in these days :) 

I will keep you with some news as soon as possible

**Comment by ahagenbruch** [comment] 2015-04-15 16:59
Sorry for the SPARQL endpoint being unavailable at the moment, but we had a massive power outage this afternoon and I can't restart the machine before tomorrow morning...

**Comment by agazzarini** [comment] 2015-04-15 17:01
No problem at all, because at the moment I'm fighting with a production issue in another project, so tomorrow sounds good

**Comment by agazzarini** [comment] 2015-04-16 09:03
Hi @ahagenbruch, the issue has been fixed in master branch, please get the latest version and  retry. 
I reproduced your scenarios and fix a couple of hidden things that happened at query time, many thanks.

Please leave the issue open as I'm working on integration tests on a parallel branch and I added some verification tests for this scenario. Unfortunately they are not yet visible in the master because I didn't merge (I had to finish a couple of things before). After integrating in the master if we are all happy I'll close the issue.

**Comment by agazzarini** [comment] 2015-04-16 14:16
Hi @ahagenbruch, I'm closing this issue as I integrated an integration test case that verifies and validates the behaviour described in this issue. 

In case you get some other issue related with this matter, please reopen the issue.

**Closed by agazzarini** 2015-04-16 14:16 UTC
Labels: bug

**Comment by ahagenbruch** [comment] 2015-04-16 15:17
Hi @agazzarini, works like a charm now, thanks a lot...
